# Generated by Django 5.2.5 on 2025-08-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(choices=[('professional', 'Professional Trust (Navy & Teal)'), ('minimal', 'Modern Minimal (Charcoal & Blue)'), ('warm', 'Warm Professional (Brown & Orange)')], default='professional', max_length=50)),
                ('primary_color', models.CharField(default='#1e3a5f', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', max_length=7)),
                ('accent_color', models.CharField(default='#0891b2', max_length=7)),
                ('background_color', models.CharField(default='#fafafa', max_length=7)),
                ('surface_color', models.CharField(default='#ffffff', max_length=7)),
                ('success_color', models.CharField(default='#10b981', max_length=7)),
                ('warning_color', models.CharField(default='#f59e0b', max_length=7)),
                ('error_color', models.CharField(default='#ef4444', max_length=7)),
                ('info_color', models.CharField(default='#3b82f6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
