# Generated by Django 5.2.5 on 2025-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('professional', 'Professional'), ('project', 'Project'), ('award', 'Award'), ('publication', 'Publication')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', '-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_lifetime', models.BooleanField(default=False)),
                ('verification_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Your professional summary')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('specializations', models.TextField(blank=True, help_text='Comma-separated list of specializations')),
                ('key_strengths', models.TextField(blank=True, help_text='Comma-separated list of key strengths')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Summary',
                'verbose_name_plural': 'Professional Summaries',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(help_text='e.g., Master of Technology, Bachelor of Engineering', max_length=100)),
                ('field_of_study', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('grade_type', models.CharField(choices=[('cgpa', 'CGPA'), ('percentage', 'Percentage'), ('grade', 'Grade'), ('gpa', 'GPA')], default='cgpa', max_length=50)),
                ('grade_value', models.CharField(blank=True, help_text='e.g., 9.30/10.0, 68%, First Class', max_length=50)),
                ('thesis_title', models.CharField(blank=True, max_length=500)),
                ('relevant_coursework', models.TextField(blank=True, help_text='Comma-separated list of relevant courses')),
                ('honors_awards', models.TextField(blank=True, help_text='Comma-separated list of honors and awards')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume Education',
                'ordering': ['display_order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('key_responsibilities', models.JSONField(default=list, help_text='List of key responsibilities')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of key achievements')),
                ('technologies_used', models.CharField(blank=True, help_text='Comma-separated list of technologies', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume Experience',
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical Skills'), ('software', 'Software & Tools'), ('professional', 'Professional Skills'), ('languages', 'Languages'), ('certifications', 'Certifications')], max_length=50)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('proficiency_percentage', models.PositiveIntegerField(default=50, help_text='Skill proficiency (0-100)')),
                ('years_experience', models.PositiveIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume Skill',
                'ordering': ['category', 'display_order', '-proficiency_percentage'],
            },
        ),
    ]
