# Generated by Django 5.2.5 on 2025-08-23 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_certification_professionalsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('civil', 'Civil Engineering'), ('environmental', 'Environmental Engineering'), ('design', 'Design & Planning'), ('construction', 'Construction Management'), ('consulting', 'Consulting Services')], default='civil', max_length=50)),
                ('short_description', models.CharField(help_text='Brief description for service cards', max_length=300)),
                ('description', models.TextField(help_text='Detailed service description')),
                ('icon', models.CharField(default='briefcase', help_text='Lucide icon name', max_length=50)),
                ('features', models.JSONField(default=list, help_text='List of key features')),
                ('process_steps', models.JSONField(default=list, help_text='Service delivery process steps')),
                ('deliverables', models.JSONField(default=list, help_text='What clients receive')),
                ('timeline', models.CharField(blank=True, help_text='Typical project duration', max_length=200)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_bom', models.BooleanField(default=False, help_text='Service includes Bill of Materials')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_templates', to='main.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Materials', max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specification', models.CharField(blank=True, max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('nos', 'Numbers'), ('kg', 'Kilograms'), ('mt', 'Metric Tons'), ('sqm', 'Square Meters'), ('cum', 'Cubic Meters'), ('lm', 'Linear Meters'), ('hrs', 'Hours'), ('days', 'Days'), ('lot', 'Lot/Lump Sum')], default='nos', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.servicebom')),
            ],
            options={
                'ordering': ['category', 'display_order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('project_title', models.CharField(max_length=300)),
                ('requirements', models.JSONField(default=dict, help_text='Client requirements data')),
                ('attachments', models.JSONField(default=list, help_text='List of uploaded file paths')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('quoted', 'Quote Sent'), ('accepted', 'Quote Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='main.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='servicebom',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='main.serviceinquiry'),
        ),
        migrations.CreateModel(
            name='ServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('terms_conditions', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='main.serviceinquiry')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number Input'), ('select', 'Select Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('date', 'Date Picker')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('choices', models.JSONField(blank=True, default=list, help_text='For select fields: list of choices')),
                ('is_required', models.BooleanField(default=False)),
                ('affects_pricing', models.BooleanField(default=False)),
                ('pricing_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.service')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('service', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('info', 'Service Information'), ('requirements', 'Requirements'), ('quote', 'Get Quote'), ('bom', 'Bill of Materials'), ('portfolio', 'Portfolio'), ('process', 'Process')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='info', help_text='Lucide icon name', max_length=50)),
                ('content', models.TextField(blank=True, help_text='Tab content (for info/process tabs)')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='main.service')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('service', 'tab_type')},
            },
        ),
    ]
