# Generated by Django 5.2.5 on 2025-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_servicebom_bomitem_serviceinquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Custom service icon/image', null=True, upload_to='services/icons/'),
        ),
    ]
