# Generated by Django 5.2.5 on 2025-08-23 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the deliverable', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the deliverable')),
                ('file', models.FileField(help_text='Secure file storage', upload_to='client_deliverables/')),
                ('file_type', models.CharField(blank=True, help_text='File type/category', max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('preparing', 'Being Prepared'), ('ready', 'Ready for Download'), ('downloaded', 'Downloaded'), ('expired', 'Access Expired')], default='preparing', max_length=20)),
                ('access_token', models.CharField(help_text='Secure access token', max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When access expires')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=10, help_text='Maximum allowed downloads')),
                ('first_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Deliverable',
                'verbose_name_plural': 'Client Deliverables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Auto-generated order number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Service Requested'), ('quoted', 'Quote Provided'), ('approved', 'Quote Approved'), ('in_progress', 'Work In Progress'), ('review', 'Under Review'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('service_inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.serviceinquiry')),
            ],
            options={
                'verbose_name': 'Client Order',
                'verbose_name_plural': 'Client Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_update', 'Order Status Update'), ('delivery_ready', 'Deliverable Ready'), ('payment_due', 'Payment Due'), ('system', 'System Notification'), ('promotional', 'Promotional')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientdeliverable')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientorder')),
            ],
            options={
                'verbose_name': 'Client Notification',
                'verbose_name_plural': 'Client Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message_type', models.CharField(choices=[('inquiry', 'General Inquiry'), ('support', 'Support Ticket'), ('order_related', 'Order Related'), ('billing', 'Billing Question'), ('technical', 'Technical Issue')], default='inquiry', max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_client', 'Waiting for Client Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('admin_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='client_messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_messages', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.clientorder')),
            ],
            options={
                'verbose_name': 'Client Message',
                'verbose_name_plural': 'Client Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientdeliverable',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='main.clientorder'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(help_text='Mobile number for login and OTP', max_length=15, unique=True)),
                ('company', models.CharField(blank=True, help_text='Company/Organization name', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Complete address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('preferred_communication', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both Email and SMS')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
    ]
