# Generated by Django 5.2.5 on 2025-08-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_clientdeliverable_clientorder_clientnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('about', 'About Section'), ('services', 'Services Preview'), ('portfolio', 'Portfolio Showcase'), ('testimonials', 'Testimonials'), ('contact', 'Contact Section'), ('stats', 'Statistics Section'), ('skills', 'Skills Section')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['order', 'section_type'],
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, help_text='Main headline for hero section', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtitle for hero section', max_length=300)),
                ('hero_description', models.TextField(blank=True, help_text='Hero description text')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('hero_cta_primary_text', models.CharField(blank=True, default='View Portfolio', max_length=50)),
                ('hero_cta_primary_url', models.CharField(blank=True, default='/portfolio/', max_length=200)),
                ('hero_cta_secondary_text', models.CharField(blank=True, default='Contact Me', max_length=50)),
                ('hero_cta_secondary_url', models.CharField(blank=True, default='/contact/', max_length=200)),
                ('about_title', models.CharField(blank=True, default='About Me', max_length=200)),
                ('about_description', models.TextField(blank=True, help_text='About section description')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='homepage/about/')),
                ('about_years_experience', models.IntegerField(blank=True, null=True)),
                ('about_projects_completed', models.IntegerField(blank=True, null=True)),
                ('about_clients_served', models.IntegerField(blank=True, null=True)),
                ('services_title', models.CharField(blank=True, default='My Services', max_length=200)),
                ('services_subtitle', models.CharField(blank=True, max_length=300)),
                ('services_description', models.TextField(blank=True)),
                ('portfolio_title', models.CharField(blank=True, default='My Work', max_length=200)),
                ('portfolio_subtitle', models.CharField(blank=True, max_length=300)),
                ('portfolio_description', models.TextField(blank=True)),
                ('testimonials_title', models.CharField(blank=True, default='What Clients Say', max_length=200)),
                ('testimonials_subtitle', models.CharField(blank=True, max_length=300)),
                ('testimonials_description', models.TextField(blank=True)),
                ('contact_title', models.CharField(blank=True, default='Get In Touch', max_length=200)),
                ('contact_subtitle', models.CharField(blank=True, max_length=300)),
                ('contact_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('contact_linkedin_url', models.URLField(blank=True)),
                ('contact_facebook_url', models.URLField(blank=True)),
                ('contact_twitter_url', models.URLField(blank=True)),
                ('contact_instagram_url', models.URLField(blank=True)),
                ('stats_title', models.CharField(blank=True, default='By The Numbers', max_length=200)),
                ('stats_subtitle', models.CharField(blank=True, max_length=300)),
                ('skills_title', models.CharField(blank=True, default='Skills & Expertise', max_length=200)),
                ('skills_subtitle', models.CharField(blank=True, max_length=300)),
                ('skills_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_projects', models.ManyToManyField(blank=True, help_text='Select projects to feature on homepage', to='main.project')),
                ('featured_services', models.ManyToManyField(blank=True, help_text='Select services to feature on homepage', to='main.service')),
                ('featured_skills', models.ManyToManyField(blank=True, help_text='Select skills to feature on homepage', to='main.skill')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='main.homepagesection')),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Contents',
            },
        ),
    ]
