# Generated by Django 5.2.5 on 2025-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homepagesection_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat1_label',
            field=models.CharField(blank=True, default='Projects Completed', help_text='First stat label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat1_number',
            field=models.CharField(blank=True, default='50+', help_text='First stat number', max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat2_label',
            field=models.CharField(blank=True, default='Years Experience', help_text='Second stat label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat2_number',
            field=models.CharField(blank=True, default='5+', help_text='Second stat number', max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat3_label',
            field=models.CharField(blank=True, default='Patent Illustrations', help_text='Third stat label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat3_number',
            field=models.CharField(blank=True, default='30+', help_text='Third stat number', max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat4_label',
            field=models.CharField(blank=True, default='Client Satisfaction', help_text='Fourth stat label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_stat4_number',
            field=models.CharField(blank=True, default='100%', help_text='Fourth stat number', max_length=10),
        ),
    ]
