# Generated by Django 5.2.5 on 2025-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_hero_stats_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact1_label',
            field=models.CharField(blank=True, default='Experience', help_text='First fact label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact1_value',
            field=models.CharField(blank=True, default='5+ Years', help_text='First fact value', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact2_label',
            field=models.CharField(blank=True, default='Projects Completed', help_text='Second fact label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact2_value',
            field=models.CharField(blank=True, default='50+', help_text='Second fact value', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact3_label',
            field=models.CharField(blank=True, default='Specialization', help_text='Third fact label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact3_value',
            field=models.CharField(blank=True, default='Civil Engineering', help_text='Third fact value', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact4_label',
            field=models.CharField(blank=True, default='Location', help_text='Fourth fact label', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_fact4_value',
            field=models.CharField(blank=True, default='India', help_text='Fourth fact value', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_point1',
            field=models.CharField(blank=True, default='Professional Engineering Design', help_text='First key point', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_point2',
            field=models.CharField(blank=True, default='Technical Patent Illustrations', help_text='Second key point', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_point3',
            field=models.CharField(blank=True, default='Environmental Engineering Solutions', help_text='Third key point', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_point4',
            field=models.CharField(blank=True, default='Sustainable Development Practices', help_text='Fourth key point', max_length=100),
        ),
    ]
