# Generated by Django 5.2.5 on 2025-08-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_about_section_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Sumithra KP - Civil Engineer & Patent Illustrator', help_text='Main site title for browser tab', max_length=100)),
                ('meta_description', models.TextField(default='Professional Civil Engineer specializing in design, patent illustrations, and environmental engineering solutions.', help_text='SEO meta description', max_length=300)),
                ('meta_keywords', models.CharField(default='civil engineering, patent illustrations, environmental engineering, sumithra kp', help_text='SEO keywords (comma-separated)', max_length=200)),
                ('og_url', models.URLField(default='https://sumithrakp.com', help_text='Open Graph URL')),
                ('logo_alt_text', models.CharField(default='Sumithra KP', help_text='Logo alt text', max_length=50)),
                ('logo_fallback_text', models.CharField(default='Sumithra KP', help_text='Text shown if logo fails to load', max_length=50)),
                ('footer_company_name', models.CharField(default='Sumithra KP', help_text='Company name in footer', max_length=50)),
                ('footer_description', models.TextField(default='Civil Engineer specializing in design, patent illustrations, and environmental engineering solutions.', help_text='Company description in footer', max_length=200)),
                ('footer_copyright_year', models.IntegerField(default=2024, help_text='Copyright year')),
                ('footer_copyright_text', models.CharField(default='All rights reserved.', help_text='Copyright text after year', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('email_address', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('footer_service1', models.CharField(default='Civil Engineering Design', help_text='First footer service', max_length=50)),
                ('footer_service2', models.CharField(default='Patent Illustrations', help_text='Second footer service', max_length=50)),
                ('footer_service3', models.CharField(default='Environmental Engineering', help_text='Third footer service', max_length=50)),
                ('business_address', models.TextField(blank=True, help_text='Business address for footer')),
                ('business_phone', models.CharField(blank=True, help_text='Business phone number', max_length=20)),
                ('business_email', models.EmailField(blank=True, help_text='Business email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
