# Generated by Django 5.2.5 on 2025-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_add_site_settings_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='availability_description',
            field=models.TextField(default='I am currently available for select consulting projects that can be done alongside my full-time position.', help_text='Availability description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='availability_note',
            field=models.CharField(default='Please contact me with project details to discuss availability and timelines.', help_text='Availability note', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='availability_title',
            field=models.CharField(default='Current Availability', help_text='Availability section title', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_company',
            field=models.CharField(default='Sigvitas & Company', help_text='Current company/employment', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title',
            field=models.CharField(default='Send a Message', help_text='Contact form section title', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_info_title',
            field=models.CharField(default='Get in Touch', help_text='Contact info section title', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_location',
            field=models.CharField(default='Mysore, Karnataka, India', help_text='Business location', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_subtitle',
            field=models.TextField(default="Let's discuss your project and how I can help bring your vision to life with professional engineering expertise.", help_text='Contact page subtitle/description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title',
            field=models.CharField(default='Contact Me', help_text='Contact page main title', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_primary_email',
            field=models.EmailField(default='contact@sumithrakp.com', help_text='Primary contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_primary_phone',
            field=models.CharField(default='+91 829 624 4110', help_text='Primary contact phone', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_response_time',
            field=models.CharField(default='I typically respond to inquiries within 24-48 hours.', help_text='Response time description', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_success_message',
            field=models.CharField(default='Thank you! Your message has been sent successfully.', help_text='Form success message', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_success_note',
            field=models.CharField(default='I typically respond within 24-48 hours.', help_text='Additional note after success message', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description',
            field=models.TextField(default="Let's discuss your project requirements and explore how I can help achieve your engineering goals.", help_text='Call to action description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_email_button_text',
            field=models.CharField(default='Email Me', help_text='Email button text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_phone_button_text',
            field=models.CharField(default='Call Now', help_text='Phone button text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(default='Ready to Get Started?', help_text='Call to action section title', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_answer_1',
            field=models.TextField(default='I specialize in civil engineering design, patent illustrations, environmental engineering solutions, residential and commercial building design, infrastructure planning, and technical documentation for patent applications.', help_text='First FAQ answer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_answer_2',
            field=models.TextField(default='Project timelines vary based on scope and complexity. Simple patent illustrations may take 1-2 weeks, while comprehensive building designs can take 4-8 weeks. I provide detailed timelines during initial consultation.', help_text='Second FAQ answer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_answer_3',
            field=models.TextField(default='Yes, I provide ongoing support to ensure successful project implementation. This includes answering questions, minor revisions, and assistance with regulatory submissions when needed.', help_text='Third FAQ answer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_answer_4',
            field=models.TextField(default='I use industry-standard software including AutoCAD, MS Visio, Civil 3D, GIS software, remote sensing tools, and AERMOD for environmental modeling. All deliverables are provided in standard formats.', help_text='Fourth FAQ answer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_question_1',
            field=models.CharField(default='What types of projects do you work on?', help_text='First FAQ question', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_question_2',
            field=models.CharField(default='What is your typical project timeline?', help_text='Second FAQ question', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_question_3',
            field=models.CharField(default='Do you provide ongoing support after project completion?', help_text='Third FAQ question', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_question_4',
            field=models.CharField(default='What software and tools do you use?', help_text='Fourth FAQ question', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_subtitle',
            field=models.CharField(default='Common questions about my services and process', help_text='FAQ section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_title',
            field=models.CharField(default='Frequently Asked Questions', help_text='FAQ section title', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='professional_services_title',
            field=models.CharField(default='Professional Services', help_text='Professional services section title', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_time_description',
            field=models.CharField(default='I typically respond to all inquiries within 24-48 hours.', help_text='Response time description', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_time_hours',
            field=models.CharField(default='24-48', help_text='Response time in hours', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_time_title',
            field=models.CharField(default='Response Time', help_text='Response time section title', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_item_1',
            field=models.CharField(default='Civil Engineering Consultation', help_text='First service item', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_item_2',
            field=models.CharField(default='AERMOD Modeling and Environmental Analysis', help_text='Second service item', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_item_3',
            field=models.CharField(default='Building Design and Layout Planning', help_text='Third service item', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_item_4',
            field=models.CharField(default='Patent Illustrations and Technical Drawings', help_text='Fourth service item', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_item_5',
            field=models.CharField(default='Construction Project Management', help_text='Fifth service item', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_availability_subtitle',
            field=models.CharField(default='Professional consulting services with flexible scheduling', help_text='Services section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_availability_title',
            field=models.CharField(default='Services & Availability', help_text='Services section title', max_length=50),
        ),
    ]
