# Generated by Django 5.2.5 on 2025-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_add_contact_page_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_1_text',
            field=models.CharField(default='Home', help_text='First quick link text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_1_url',
            field=models.CharField(default='/', help_text='First quick link URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_2_text',
            field=models.CharField(default='Resume', help_text='Second quick link text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_2_url',
            field=models.CharField(default='/resume', help_text='Second quick link URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_3_text',
            field=models.CharField(default='Portfolio', help_text='Third quick link text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_3_url',
            field=models.CharField(default='/portfolio', help_text='Third quick link URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_4_text',
            field=models.CharField(default='Services', help_text='Fourth quick link text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_4_url',
            field=models.CharField(default='/services', help_text='Fourth quick link URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_5_text',
            field=models.CharField(default='Contact', help_text='Fifth quick link text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_5_url',
            field=models.CharField(default='/contact', help_text='Fifth quick link URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_6_text',
            field=models.CharField(blank=True, help_text='Sixth quick link text (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_6_url',
            field=models.CharField(blank=True, help_text='Sixth quick link URL (optional)', max_length=100),
        ),
    ]
