# Generated by Django 5.2.5 on 2025-08-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_quick_links_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_1_text',
            field=models.CharField(blank=True, help_text='First quick link text (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_1_url',
            field=models.CharField(blank=True, help_text='First quick link URL (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_2_text',
            field=models.CharField(blank=True, help_text='Second quick link text (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_2_url',
            field=models.CharField(blank=True, help_text='Second quick link URL (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_3_text',
            field=models.CharField(blank=True, help_text='Third quick link text (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_3_url',
            field=models.CharField(blank=True, help_text='Third quick link URL (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_4_text',
            field=models.CharField(blank=True, help_text='Fourth quick link text (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_4_url',
            field=models.CharField(blank=True, help_text='Fourth quick link URL (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_5_text',
            field=models.CharField(blank=True, help_text='Fifth quick link text (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quick_link_5_url',
            field=models.CharField(blank=True, help_text='Fifth quick link URL (optional)', max_length=100),
        ),
    ]
