# Generated by Django 5.2.5 on 2025-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_make_quick_links_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='featured_testimonials',
            field=models.ManyToManyField(blank=True, help_text='Select testimonials to feature on homepage', to='main.testimonial'),
        ),
    ]
