# Generated by Django 5.2.5 on 2025-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_featured_testimonials_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_cta_primary_text',
            field=models.CharField(blank=True, default='Contact Me Today', help_text='Primary CTA button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_cta_primary_url',
            field=models.CharField(blank=True, default='/contact', help_text='Primary CTA button URL', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_cta_secondary_text',
            field=models.CharField(blank=True, default='View My Work', help_text='Secondary CTA button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_cta_secondary_url',
            field=models.CharField(blank=True, default='/portfolio', help_text='Secondary CTA button URL', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_description',
            field=models.TextField(blank=True, default="Let's work together to bring your engineering vision to life with professional expertise and innovative solutions."),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_title',
            field=models.CharField(blank=True, default='Ready to Start Your Project?', max_length=200),
        ),
    ]
