# Generated by Django 5.2.5 on 2025-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_add_contact_cta_button_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='testimonials_display_mode',
            field=models.CharField(choices=[('grid', 'Static Grid (3 columns)'), ('slider', 'Slider with Navigation'), ('continuous', 'Continuous Horizontal Scroll')], default='grid', help_text='Choose how testimonials are displayed on the homepage', max_length=20),
        ),
    ]
