# Generated by Django 5.2.5 on 2025-08-23 19:35

from django.db import migrations


def migrate_skill_categories(apps, schema_editor):
    """Copy data from skill_category to category field"""
    ResumeSkill = apps.get_model('main', 'ResumeSkill')
    
    for skill in ResumeSkill.objects.all():
        if skill.skill_category:
            # This is a data migration, the field names here refer to database columns
            # We need to copy skill_category_id to category_id
            skill.category_id = skill.skill_category_id
            skill.save()


def reverse_migrate_skill_categories(apps, schema_editor):
    """Reverse migration - not implementing as this is a one-way migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_skillcategory_resumeskill_skill_category'),
    ]

    operations = [
        migrations.RunPython(migrate_skill_categories, reverse_migrate_skill_categories),
    ]
