# Generated by Django 5.2.5 on 2025-08-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20250823_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeskill',
            options={'ordering': ['category__display_order', 'display_order', '-proficiency_percentage'], 'verbose_name': 'Resume Skill'},
        ),
        migrations.RemoveField(
            model_name='resumeskill',
            name='skill_category',
        ),
        migrations.AlterField(
            model_name='resumeskill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillcategory'),
        ),
    ]
