# Generated by Django 5.2.5 on 2025-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_resumeskill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Optional company name', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sender', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('is_replied', models.BooleanField(default=False, help_text='Whether the message has been replied to')),
                ('reply_notes', models.TextField(blank=True, help_text='Internal notes for replies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
