# Generated by Django 5.2.5 on 2025-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='response_feature_1',
            field=models.CharField(default='Quick response within 24-48 hours', help_text='First response feature', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_feature_2',
            field=models.CharField(default='Professional consultation guaranteed', help_text='Second response feature', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_feature_3',
            field=models.CharField(default='Detailed project analysis provided', help_text='Third response feature', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_feature_4',
            field=models.CharField(default='Free initial consultation call', help_text='Fourth response feature', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_feature_5',
            field=models.CharField(default='Transparent pricing and timelines', help_text='Fifth response feature', max_length=100),
        ),
    ]
