# Generated by Django 5.2.5 on 2026-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_sitesettings_response_feature_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client/Company name', max_length=200)),
                ('logo', models.ImageField(help_text='Client logo image', upload_to='clients/')),
                ('website', models.URLField(blank=True, help_text='Client website URL (optional)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which logos appear')),
                ('is_active', models.BooleanField(default=True, help_text='Show this logo on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Logo',
                'verbose_name_plural': 'Client Logos',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
