# Generated by Django 5.2.5 on 2026-08-15 20:38

import django.db.models.deletion
import main.models
import main.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_client_logo_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='ai_daily_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Per-client daily AI generation limit override (blank = use each feature's default)", null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Allow this client to use AI features'),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Linked client account, when the inquiry came from a logged-in client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientdeliverable',
            name='expires_at',
            field=models.DateTimeField(default=main.models.default_deliverable_expiry, help_text='When access expires'),
        ),
        migrations.AlterField(
            model_name='clientdeliverable',
            name='file',
            field=models.FileField(help_text='Private file storage (not URL-served)', storage=main.storage.PrivateMediaStorage(), upload_to='client_deliverables/'),
        ),
    ]
