# Generated by Django 5.2.5 on 2026-08-15 20:55

import django.db.models.deletion
import main.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_portal_security_foundations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('adapter_type', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai_compatible', 'OpenAI-compatible (generic)'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('seedance', 'Seedance (video)'), ('wan', 'WAN / Alibaba (video)'), ('higgsfield', 'Higgsfield (video)')], max_length=30)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('multimodal', 'Multimodal')], default='text', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('base_url', models.URLField(blank=True, help_text="Override the adapter's default endpoint")),
                ('default_model', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Adapter knobs: max_tokens, timeout, submit_path/poll_path for video, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAIFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(help_text='Client-facing explanation of what this tool does')),
                ('feature_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('model_override', models.CharField(blank=True, max_length=100)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField(help_text='Use {field_name} placeholders matching input field names')),
                ('input_fields', models.JSONField(default=list, help_text='[{"name","label","type","required","choices","help"}] - type: text/textarea/select/number/file')),
                ('output_guidance', models.TextField(blank=True, help_text='Appended to the system prompt (formatting rules)')),
                ('allow_file_upload', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('daily_limit_per_client', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='main.aiprovider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_features', to='main.service')),
            ],
            options={
                'verbose_name': 'Service AI Feature',
                'ordering': ['display_order', 'title'],
                'unique_together': {('service', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(blank=True, max_length=200)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('input_file', models.FileField(blank=True, null=True, storage=main.storage.PrivateMediaStorage(), upload_to='ai_inputs/%Y/%m/')),
                ('rendered_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('output_text', models.TextField(blank=True)),
                ('output_file', models.FileField(blank=True, null=True, storage=main.storage.PrivateMediaStorage(), upload_to='ai_outputs/%Y/%m/')),
                ('output_mime', models.CharField(blank=True, max_length=50)),
                ('provider_job_id', models.CharField(blank=True, max_length=200)),
                ('tokens_input', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_output', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clientorder')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='main.serviceaifeature')),
            ],
            options={
                'verbose_name': 'AI Generation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='main_aigene_client__c30339_idx')],
            },
        ),
    ]
