# Generated by Django 5.2.5 on 2026-08-15 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_ai_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_type', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('manual', 'Manual / UPI')], max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('key_id', models.CharField(blank=True, help_text='Razorpay Key ID / Stripe publishable key', max_length=255)),
                ('key_secret', models.CharField(blank=True, help_text='Razorpay Key Secret / Stripe secret key', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Manual gateway: {"upi_id", "bank_name", "account_no", "ifsc", "account_name", "note"}')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending Confirmation'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=10)),
                ('gateway_order_id', models.CharField(blank=True, max_length=200)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200)),
                ('gateway_signature', models.CharField(blank=True, max_length=300)),
                ('reference_note', models.CharField(blank=True, help_text='UPI/bank reference submitted by the client (manual payments)', max_length=200)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.paymentgateway')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.clientorder')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
